-- Crear tabla users
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       password VARCHAR(255) NOT NULL,
                       username VARCHAR(255) NOT NULL UNIQUE
);

-- Crear tabla alert
CREATE TABLE alert (
                       comparison_type INTEGER NOT NULL,
                       price NUMERIC(38,2) NOT NULL,
                       version INTEGER NOT NULL,
                       asset VARCHAR(255) NOT NULL,
                       PRIMARY KEY (comparison_type, price, asset)
);

-- Crear tabla alert_user
CREATE TABLE alert_user (
                            comparison_type INTEGER NOT NULL,
                            price NUMERIC(38,2) NOT NULL,
                            user_id BIGINT NOT NULL,
                            asset VARCHAR(255) NOT NULL
);

-- Foreign key de alert_user hacia users
ALTER TABLE alert_user
    ADD CONSTRAINT FK_alert_user_user_id FOREIGN KEY (user_id) REFERENCES users(id);

-- Foreign key de alert_user hacia alert (compuesta)
ALTER TABLE alert_user
    ADD CONSTRAINT FK_alert_user_alert FOREIGN KEY (comparison_type, price, asset) REFERENCES alert(comparison_type, price, asset);
