name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Maven Build & Test ✅
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_RYUK_DISABLED: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker availability
        run: docker info

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.8'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn clean verify

  deploy:
    name: Deploy to ECS 🚀
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719830632894:role/github
          aws-region: eu-west-3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 719830632894.dkr.ecr.eu-west-3.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -f ./infrastructure/Dockerfile -t kinesisflow .

      - name: Tag Docker image
        run: |
          docker tag kinesisflow:latest 719830632894.dkr.ecr.eu-west-3.amazonaws.com/kinesisflow:latest

      - name: Push Docker image to ECR
        run: |
          docker push 719830632894.dkr.ecr.eu-west-3.amazonaws.com/kinesisflow:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster gentle-turtle-fa4hpz \
            --service kinesisflow-service-2nstaxjv \
            --region eu-west-3 \
            --force-new-deployment
          echo "✅ Deployment initiated successfully"
